#SingleInstance force

:*:&grinning;::😀
:*:&grinning_smiling_eyes;::😁
:*:&grinning_tears;::😂
:*:&smiling_open_mouth;::😃
:*:&smiling_mouth_eyes;::😄
:*:&smiling_mouth_sweat;::😅
:*:&smiling_mouth_closed_eyes;::😆
:*:&winking;::😉
:*:&smiling_eyes;::😊
:*:&savouring;::😋
:*:&sunglasses;::😎
:*:&heart_eyes;::😍
:*:&blow_kiss;::😘
:*:&kissing;::😗
:*:&kissing_smiling_eyes;::😙
:*:&kissing_closed_eyes;::😚
:*:&slight_smile;::🙂
:*:&hugging_face;::🤗
:*:&halo;::😇
:*:&nerd;::🤓
:*:&thinking;::🤔
:*:&neutral;::😐
:*:&no_mouth;::😶
:*:&rolling_eyes;::🙄
:*:&smirking;::😏
:*:&perservering;::😣
:*:&disappointed_relieved;::😥
:*:&open_mouth;::😮
:*:&zipper;::🤐
:*:&hushed;::😯
:*:&sleepy;::😪
:*:&tired;::😫
:*:&sleeping;::😴
:*:&relieved;::😌
:*:&tongue;::😛
:*:&tongue_wink;::😜
:*:&tongue_closed_eyes;::😝
:*:&unamused;::😒
:*:&cold_sweat;::😓
:*:&pensive;::😔
:*:&confused;::😕
:*:&upside_down;::🙃
:*:&money_mouth;::🤑
:*:&astonished;::😲
:*:&medical_mask;::😷
:*:&thermometer_face;::🤒
:*:&head_bandage;::🤕
:*:&slight_frown;::🙁
:*:&confounded;::😖
:*:&disappointed;::😞
:*:&worried;::😟
:*:&triumph;::😤
:*:&crying;::😢
:*:&loud_crying;::😭
:*:&frowning_open_mouth;::😦
:*:&anguished;::😧
:*:&fearful;::😨
:*:&weary;::😩
:*:&grimacing;::😬
:*:&open_mouth_cold_sweat;::😰
:*:&screaming_in_fear;::😱
:*:&flushed;::😳
:*:&dizzy;::😵
:*:&pouting;::😡
:*:&angry;::😠
:*:&smiling_with_horns;::😈