#SingleInstance force

:*:&grinning;::😀
:*:&grinning_smiling_eyes;::😁
:*:&grinning_tears;::😂
:*:&smiling_open_mouth;::😃
:*:&smiling_mouth_eyes;::😄
:*:&smiling_mouth_sweat;::😅
:*:&smiling_mouth_closed_eyes;::😆
:*:&winking;::😉
:*:&smiling_eyes;::😊
:*:&savouring;::😋
:*:&sunglasses;::😎
:*:&heart_eyes;::😍
:*:&blow_kiss;::😘
:*:&kissing;::😗
:*:&kissing_smiling_eyes;::😙
:*:&kissing_closed_eyes;::😚
:*:&slight_smile;::🙂
:*:&hugging_face;::🤗
:*:&halo;::😇
:*:&nerd;::🤓
:*:&thinking;::🤔
:*:&neutral;::😐
:*:&no_mouth;::😶
:*:&rolling_eyes;::🙄
:*:&smirking;::😏
:*:&perservering;::😣
:*:&disappointed_relieved;::😥
:*:&open_mouth;::😮
:*:&zipper;::🤐
:*:&hushed;::😯
:*:&sleepy;::😪
:*:&tired;::😫
:*:&sleeping;::😴
:*:&relieved;::😌
:*:&tongue;::😛
:*:&tongue_wink;::😜
:*:&tongue_closed_eyes;::😝
:*:&unamused;::😒
:*:&cold_sweat;::😓
:*:&pensive;::😔
:*:&confused;::😕
:*:&upside_down;::🙃
:*:&money_mouth;::🤑
:*:&astonished;::😲
:*:&medical_mask;::😷
:*:&thermometer_face;::🤒
:*:&head_bandage;::🤕
:*:&slight_frown;::🙁
:*:&confounded;::😖
:*:&disappointed;::😞
:*:&worried;::😟
:*:&triumph;::😤
:*:&crying;::😢
:*:&loud_crying;::😭
:*:&frowning_open_mouth;::😦
:*:&anguished;::😧
:*:&fearful;::😨
:*:&weary;::😩
:*:&grimacing;::😬
:*:&open_mouth_cold_sweat;::😰
:*:&screaming_in_fear;::😱
:*:&flushed;::😳
:*:&dizzy;::😵
:*:&pouting;::😡
:*:&angry;::😠
:*:&smiling_with_horns;::😈
:*:&imp;::👿
:*:&japanese_ogre;::👹
:*:&japanese_goblin;::👺
:*:&skull;::💀
:*:&ghost;::👻
:*:&extraterrestrial_alien;::👽
:*:&robot_face;::🤖
:*:&poop;::💩
:*:&smiling_cat;::😺
:*:&grinning_cat;::😸
:*:&tears_of_joy_cat;::😹
:*:&heart_eyes_cat;::😻
:*:&wry_cat;::😼
:*:&kissing_cat;::😽
:*:&weary_cat;::🙀
:*:&crying_cat;::😿
:*:&pouting_cat;::😾
:*:&boy;::👦
:*:&girl;::👧
:*:&man;::👨
:*:&woman;::👩
:*:&old_man;::👴
:*:&old_woman;::👵
:*:&baby;::👶
:*:&person_blonde_hair;::👱
:*:&police_officer;::👮
:*:&gua_pi_mao_man;::👲
:*:&turban_man;::👳
:*:&construction_worker;::👷
:*:&white_cross_helmet_man;::⛑
:*:&princess;::👸
:*:&guardsman;::💂
:*:&spy;::🕵
:*:&santa;::🎅
:*:&bride;::👰
:*:&baby_angel;::👼
:*:&face_massage;::💆
:*:&haircut;::💇
:*:&frowning_person;::🙍
:*:&pouting_person;::🙎
:*:&no_good_gesture;::🙅
:*:&ok_gesture;::🙆
:*:&information_desk_person;::💁
:*:&raising_one_hand;::🙋
:*:&bowing_deeply;::🙇
:*:&raising_both_hands;::🙌
:*:&folded_hands;::🙏
:*:&speaking_head_silhouette;::🗣
:*:&bust_silhouette;::👤
:*:&busts_silhouette;::👥
:*:&pedestrian;::🚶
:*:&runner;::🏃
:*:&bunny_ears_woman;::👯
:*:&dancer;::💃
:*:&levitating_business_suit_man;::🕴
:*:&man_woman_holding_hands;::👫
:*:&man_man_holding_hands;::👬
:*:&woman_woman_holding_hands;::👭
:*:&kiss_man_woman;::💏
:*:&kiss_man_man;::👨‍❤️‍💋‍👨
:*:&kiss_woman_woman;::👩‍❤️‍💋‍👩
:*:&couple_woman_man;::💑
:*:&couple_man_man;::👨‍❤️‍👨
:*:&couple_woman_woman;::👩‍❤️‍👩
:*:&fam_man_woman_boy;::👪
:*:&fam_man_woman_girl;::👨‍👩‍👧
:*:&fam_man_woman_girl_boy;::👨‍👩‍👧‍👦
:*:&fam_man_woman_boy_boy;::👨‍👩‍👦‍👦
:*:&fam_man_woman_girl_girl;::👨‍👩‍👧‍👧
:*:&fam_man_man_boy;::👨‍👨‍👦
:*:&fam_man_man_girl;::👨‍👨‍👧
:*:&fam_man_man_girl_boy;::👨‍👨‍👧‍👦
:*:&fam_man_man_boy_boy;::👨‍👨‍👦‍👦
:*:&fam_man_man_girl_girl;::👨‍👨‍👧‍👧
:*:&fam_woman_woman_boy;::👩‍👩‍👦
:*:&fam_woman_woman_girl;::👩‍👩‍👧
:*:&fam_woman_woman_girl_boy;::👩‍👩‍👧‍👦
:*:&fam_woman_woman_boy_boy;::👩‍👩‍👦‍👦
:*:&fam_woman_woman_girl_girl;::👩‍👩‍👧‍👧
:*:&biceps;::💪
:*:&left_backhand_point;::👈
:*:&right_backhand_point;::👉
:*:&up_point;::☝
:*:&up_backhand_point;::👆
:*:&middle_finger;::🖕
:*:&down_backhand_point;::👇
:*:&victory_hand;::✌
:*:&spock_hand;::🖖
:*:&horns_hand;::🤘
:*:&raised_splayed_hand;::🖐
:*:&raised_hand;::✋
:*:&ok_hand;::👌
:*:&+1;::👍
:*:&-1;::👎
:*:&raised_fist;::✊
:*:&fist;::👊
:*:&waving;::👋
:*:&clapping;::👏
:*:&open_hands;::👐
:*:&writing_hand;::✍
:*:&nail_polish;::💅
:*:&ear;::👂
:*:&nose;::👃
:*:&footprints;::👣
:*:&eyes;::👀
:*:&eye;::👁
:*:&tongue;::👅
:*:&mouth;::👄
:*:&kiss_mark;::💋
:*:&glasses;::👓
:*:&sunglasses;::🕶
:*:&necktie;::👔
:*:&tshirt;::👕
:*:&jeans;::👖
:*:&dress;::👗
:*:&kimono;::👘
:*:&bikini;::👙
:*:&womans_clothes;::👚
:*:&purse;::👛
:*:&handbag;::👜
:*:&pouch;::👝
:*:&satchel;::🎒
:*:&mans_shoe;::👞
:*:&athletic_shoe;::👟
:*:&high_heel_shoe;::👠
:*:&womans_sandal;::👡
:*:&womans_boots;::👢
:*:&crown;::👑
:*:&womans_hat;::👒
:*:&top_hat;::🎩
:*:&mortarboard;::🎓
:*:&lipstick;::💄
:*:&ring;::💍
:*:&closed_umbrella;::🌂
:*:&briefcase;::💼